; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
board_build.partitions = huge_app.csv
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 9600
lib_deps = 
	adafruit/ENS160 - Adafruit Fork@^3.0.1
	ptsolns/PTSolns_AHTx@^1.0.0
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit SH110X@^2.1.14
	fbiego/ESP32Time@^2.0.6
